# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class MainGui(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(798, 575)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBox = QtWidgets.QToolBox(widget)
        self.toolBox.setObjectName("toolBox")
        self.scanParameterPage = QtWidgets.QWidget()
        self.scanParameterPage.setGeometry(QtCore.QRect(0, 0, 774, 483))
        self.scanParameterPage.setAccessibleName("")
        self.scanParameterPage.setObjectName("scanParameterPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scanParameterPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.scanParameterPage)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.scanParameterPage)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.toolBox.addItem(self.scanParameterPage, "")
        self.DataStoragePage = QtWidgets.QWidget()
        self.DataStoragePage.setGeometry(QtCore.QRect(0, 0, 774, 483))
        self.DataStoragePage.setObjectName("DataStoragePage")
        self.widget = QtWidgets.QWidget(self.DataStoragePage)
        self.widget.resize(192, 157)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(180, 80))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.DataStoragePage, "")
        self.horizontalLayout_2.addWidget(self.toolBox)

        self.retranslateUi(widget)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "P65 XAFS Scan Manager"))
        self.toolBox.setWhatsThis(_translate(
            "widget", "P65 XAFS Scan Manager"))
        self.toolBox.setAccessibleName(
            _translate("widget", "P65 XAFS Scan Manager"))
        self.toolBox.setAccessibleDescription(
            _translate("widget", "P65 XAFS Scan Manager"))
        self.pushButton.setText(_translate("widget", "Add"))
        self.pushButton_3.setText(_translate("widget", "Copy"))
        self.pushButton_2.setText(_translate("widget", "Remove"))
        self.pushButton_7.setText(_translate("widget", "Clear"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("widget", "Scan #1"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("widget", "Start"))
        self.pushButton_5.setText(_translate("widget", "Pause"))
        self.toolBox.setItemText(self.toolBox.indexOf(
            self.scanParameterPage), _translate("widget", "Scan Parameters"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("widget", "Location"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("widget", "Folder Name"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("widget", "Value"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("widget", "UserBeamtime"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("widget", "P.I."))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("widget", "Save"))
        self.label_2.setText(_translate("widget", "Data Storage"))
        self.toolBox.setItemText(self.toolBox.indexOf(
            self.DataStoragePage), _translate("widget", "Data Storage"))
